# Generated by Django 5.1 on 2024-12-14 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotaryapp', '0004_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('profession', models.CharField(blank=True, max_length=100)),
                ('age', models.CharField(blank=True, max_length=10)),
                ('phone_number', models.CharField(max_length=15)),
                ('secondary_number', models.CharField(blank=True, max_length=15)),
                ('phone_type', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
