# Generated by Django 5.1 on 2025-04-29 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotaryapp', '0010_remove_event_image_eventimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='thumbnail',
            field=models.ImageField(default=1, upload_to='events/'),
        ),
    ]
